[env:m5stick-c]
platform = espressif32@6.7.0
board = m5stick-c
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags =
    -DCORE_DEBUG_LEVEL=0

lib_deps =
    m5stack/M5StickCPlus@^0.1.0
    pololu/VL53L1X@^1.3.1
